export const ROLES = {
  ADMIN: 'ADMIN',
  AGENTE: 'AGENTE',
  CLIENTE: 'CLIENTE',
};

export const PERMISSIONS = {
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_PACKAGES: 'MANAGE_PACKAGES',
  VIEW_BOOKINGS: 'VIEW_BOOKINGS',
  CREATE_BOOKING: 'CREATE_BOOKING',
  CANCEL_BOOKING: 'CANCEL_BOOKING',
  VIEW_REPORTS: 'VIEW_REPORTS',
  MANAGE_CONTENT: 'MANAGE_CONTENT',
};

// Mapa de permisos por rol
export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_PACKAGES,
    PERMISSIONS.VIEW_BOOKINGS,
    PERMISSIONS.CREATE_BOOKING,
    PERMISSIONS.CANCEL_BOOKING,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_CONTENT,
  ],
  [ROLES.AGENTE]: [
    PERMISSIONS.MANAGE_PACKAGES,
    PERMISSIONS.VIEW_BOOKINGS,
    PERMISSIONS.CREATE_BOOKING,
    PERMISSIONS.CANCEL_BOOKING,
    PERMISSIONS.MANAGE_CONTENT,
  ],
  [ROLES.CLIENTE]: [
    PERMISSIONS.VIEW_BOOKINGS,
    PERMISSIONS.CREATE_BOOKING,
    PERMISSIONS.CANCEL_BOOKING,
  ],
};

export function hasPermission(role, permission) {
  const list = ROLE_PERMISSIONS[role] || [];
  return list.includes(permission);
}

export const ALL_PERMISSIONS_LIST = Object.values(PERMISSIONS);
